import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
import "./styles/globals.css";
=======
import "./globals.css";
>>>>>>> 56972e250ce796a309cee96737e6d93e8fbefbfa

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
<<<<<<< HEAD
  title: "Orbit",
  description: "Made By Orbit",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 56972e250ce796a309cee96737e6d93e8fbefbfa
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
